name: Build and Publish Docker Image

on:
  push:
    branches:
      - JCasC-var
    paths:
      - 'Github-oauth_using_JCasC/Jenkins-Dockerfile/plugins.txt'  # Trigger action only when plugins.txt is modified

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Github-oauth_using_JCasC/Jenkins-Dockerfile/Dockerfile
        push: true
        tags: vishnusharma11d00/jenkins-jcasc-plugin:${{ github.run_number }}

    - name: Update user_data.sh with build number
      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Define build number
        BUILD_NUMBER=${{ github.run_number }}

        # Replace the latest tag with the build number in user_data.sh
        sed -i "s|vishnusharma11d00/jenkins-jcasc-plugin:[^ ]*|vishnusharma11d00/jenkins-jcasc-plugin:${BUILD_NUMBER}|g" Github-oauth_using_JCasC/terraform/user_data.sh

        # Commit the changes
        git config user.email "vishnusharma11d00@gmail.com"
        git config user.name "GitHub Actions"
        git add Github-oauth_using_JCasC/terraform/user_data.sh
        git commit -m "Update Docker image tag to ${BUILD_NUMBER} in user_data.sh"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/VishnuSharma11D00/DevOps-CICD.git HEAD:JCasC-var

    - name: Post build cleanup
      run: docker builder prune --all --force
