name: Build and Publish Docker Image

on:
  push:
    paths:
      - 'Github-oauth_using_JCasC/Jenkins-Dockerfile/plugins.txt'  # Trigger action only when plugins.txt is modified

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Github-oauth_using_JCasC/Jenkins-Dockerfile/Dockerfile
        push: true
        tags: vishnusharma11d00/jenkins-jcasc-plugin:latest

    - name: Post build cleanup
      run: docker builder prune --all --force
